/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidationKeyTxtRouteImport } from './routes/validation-key.txt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationKeyTxtRoute = ValidationKeyTxtRouteImport.update({
  id: '/validation-key/txt',
  path: '/validation-key/txt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/validation-key/txt': typeof ValidationKeyTxtRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/validation-key/txt': typeof ValidationKeyTxtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/validation-key/txt': typeof ValidationKeyTxtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/validation-key/txt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/validation-key/txt'
  id: '__root__' | '/' | '/validation-key/txt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ValidationKeyTxtRoute: typeof ValidationKeyTxtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation-key/txt': {
      id: '/validation-key/txt'
      path: '/validation-key/txt'
      fullPath: '/validation-key/txt'
      preLoaderRoute: typeof ValidationKeyTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ValidationKeyTxtRoute: ValidationKeyTxtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
